plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

base {
	archivesName = "fabric-${project.mod_id}"
}

repositories {
	maven {
		name = "TerraformersMC"
		url = uri("https://maven.terraformersmc.com/releases/")
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"sculksight" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

configurations {
	commonJava {
		canBeResolved = true
		canBeConsumed = false
	}

	commonClientJava {
		canBeResolved = true
		canBeConsumed = false
	}
}

tasks.named('compileJava', JavaCompile) {
	dependsOn(configurations.commonJava)
	source(configurations.commonJava)
}

tasks.named('compileClientJava', JavaCompile) {
	dependsOn(configurations.commonClientJava)
	source(configurations.commonClientJava)
}

dependencies {
	commonJava project(path: ':common', configuration: 'commonJava')
	commonClientJava project(path: ':common', configuration: 'commonClientJava')

	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	clientCompileOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"
	clientRuntimeOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"

	testImplementation platform("org.junit:junit-bom:${project.junit_version}")
	testImplementation "org.junit.jupiter:junit-jupiter"

	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named('test', Test) {
	useJUnitPlatform()

	testLogging {
		events "passed", "skipped", "failed"
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version))
	}

	withSourcesJar()
}

tasks.named('sourcesJar', Jar) {
	dependsOn(configurations.commonJava, configurations.commonClientJava)
	from(configurations.commonJava)
	from(configurations.commonClientJava)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	manifest {
		attributes("Implementation-Version": project.version)
	}

	from(rootProject.file("LICENSE")) {
		rename { "LICENSE_$projectName" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
