org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Shared across every module (common, fabric, neoforge).
minecraft_version=26.2
java_version=25

# Mod properties.
version=0.4.0+26.2
group=com.scr0ols
mod_id=sculksight
mod_name=Sculk Sight

# Fabric.
# https://fabricmc.net/develop
loader_version=0.19.3
loom_version=1.17.20
fabric_api_version=0.158.0+26.2

# NeoForge.
neoforge_moddev_version=2.0.146
neo_version=26.2.0.75
neo_form_version=26.2-2
minecraft_version_range=[26.2,26.3)

junit_version=6.1.3

mod_menu_version=20.0.1
