license="${mod_license}"

issueTrackerURL="https://github.com/scr0ols/Sculk-Sight/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Renders the effective detection surface of sculk sensors as a world overlay.
'''
authors="scr0ols"
displayURL="https://modrinth.com/project/sculk-sight"
iconFile="sculksight_icon.png"
logoFile="sculksight_icon.png"
bannerFile="sculksight_banner.png"

[[dependencies.${mod_id}]]
	modId="neoforge"
	type="required"
	versionRange="[${neo_version},)"
	ordering="NONE"
	side="CLIENT"

[[dependencies.${mod_id}]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="CLIENT"
